# https://github.com/ashleve/lightning-hydra-template/blob/main/configs/trainer/default.yaml

epochs: 10

accelerator: cpu # mps, cuda
devices: 1

# mixed precision for extra speed-up
# precision: 16

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1
generate_every_n_epoch: 1
log_every_n_step: 50

save_ckpt_every_n_epoch: 1
save_ckpt_dirpath: "${paths.output_dir}/ckpt/" # directory to save the model file
save_filename: model # checkpoint filename
save_generated_filename: generated # generated image filename

best_model_path:

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False