repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: 'migrations/.*|tests/.*|utils/__init__.py'

  - repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
      - id: black
        exclude: 'migrations/.*|tests/.*|utils/__init__.py'