_target_: src.models.AutoEncoder.AutoEncoder

Encoder:
  _target_: src.models.AutoEncoder.Encoder
  input_shape: [1, 28, 28]

Decoder:
  _target_: src.models.AutoEncoder.Decoder
  output_shape: [1, 28, 28]