_target_: src.models.GAN.GAN

Generator:
  _target_: src.models.GAN.Generator
  output_shape: [1, 28, 28]
  z_dim: 64
  device: cpu

Discriminator:
  _target_: src.models.GAN.Discriminator
  input_shape: [1, 28, 28]