_target_: src.models.GAN.GAN

Generator:
  _target_: src.models.GAN.Generator
  z_dim: 100
  channels: 1
  height: 28
  width: 28
  device: cpu

Discriminator:
  _target_: src.models.GAN.Discriminator
  channels: 1
  height: 28
  width: 28