_target_: src.models.VariationalAutoEncoder.VariationalAutoEncoder

Encoder:
  _target_: src.models.VariationalAutoEncoder.Encoder
  input_shape: [1, 28, 28]
  z_dim: 64

Decoder:
  _target_: src.models.VariationalAutoEncoder.Decoder
  output_shape: [1, 28, 28]
  z_dim: 64