_target_: src.models.VariationalAutoEncoder.VariationalAutoEncoder

Encoder:
  _target_: src.models.VariationalAutoEncoder.Encoder
  channels: 1
  z_dim: 64

Decoder:
  _target_: src.models.VariationalAutoEncoder.Decoder
  channels: 1
  z_dim: 64